name = "CrypticCrosswords"
uuid = "5f016b6a-1706-11e9-24c5-5177419d09cb"
authors = ["Robin Deits <robin.deits@gmail.com>"]
version = "0.1.0"

[deps]
ChartParsers = "de988000-0167-11e9-3115-2b7bbce15f76"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WordNet = "a945a9ba-879e-550e-aa45-2a4d52798e91"

[compat]
ChartParsers = "0.0.1"
Combinatorics = "0.7"
DataDeps = "0.6"
DataStructures = "0.16, 0.17"
JSON = "0.18, 0.19, 0.20, 0.21"
ProgressMeter = "0.9, 1"
WordNet = "0.2.1"
julia = "1.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
